# Generated by Django 5.0.6 on 2024-09-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_image_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='images/'),
        ),
    ]
